version: '2'
services:
  ldap:
    image: osixia/openldap:1.1.10
    environment:
      - "LDAP_ORGANISATION=patrick246"
      - "LDAP_DOMAIN=localhost"
      - "LDAP_ADMIN_PASSWORD=adminpw"
      - "LDAP_CONFIG_PASSWORD=configpw"
      - "LDAP_READONLY_USER=true"
      - "LDAP_READONLY_USER_USERNAME=readonly"
      - "LDAP_READONLY_USER_PASSWORD=readonlypw"
    ports:
     - "389:389"